package com.zongteng.ztetl.entity.zy_wms

case class ReceivingDetail(
                            rd_id: String,
                            receiving_id: String,
                            receiving_code: String,
                            sm_code: String,
                            rd_transfer_status: String,
                            receiving_line_no: String,
                            rd_status: String,
                            receiving_exception: String,
                            receiving_exception_handle: String,
                            exception_process_instruction: String,
                            product_id: String,
                            product_barcode: String,
                            rd_receiving_qty: String,
                            rd_putaway_qty: String,
                            rd_received_qty: String,
                            rd_delivery_qty: String,
                            is_qc: String,
                            is_priority: String,
                            is_need_dev_photo: String,
                            is_need_dev_desc: String,
                            rd_note: String,
                            rd_add_time: String,
                            rd_update_time: String,
                            product_package_type: String,
                            value_added_type: String,
                            valid_date: String,
                            fba_product_code: String,
                            reference_box_no: String,
                            is_new_add: String,
                            rd_timestamp: String
                          )
