package  com.zongteng.ztetl.entity.zy_wms

case class OrderProduct (op_id: String,
                         order_id: String,
                         order_code: String,
                         product_id: String,
                         product_barcode: String,
                         op_quantity: String,
                         op_final_value_fee: String,
                         op_paypal_fee: String,
                         op_sales_price: String,
                         op_category: String,
                         op_recv_account: String,
                         op_ref_tnx: String,
                         op_ref_item_id: String,
                         op_ref_buyer_id: String,
                         op_record_id: String,
                         op_ref_paydate: String,
                         op_add_time: String,
                         op_update_time: String,
                         shared_sign: String,
                         shared_unit_price: String,
                         fba_product_code: String,
                         order_product_declared_value: String,
                         op_length: String,
                         op_width: String,
                         op_height: String,
                         op_weight: String,
                         op_timestamp: String,
                         fba_product_name: String
                        )