package com.zongteng.ztetl.entity.zy_wms

case class ReceivingBox(rb_id: String,
                        warehouse_id: String,
                        receiving_id: String,
                        receiving_code: String,
                        box_no: String,
                        box_number: String,
                        rb_transfer_status: String,
                        receiving_user_id: String,
                        check_in_user_id: String,
                        check_out_user_id: String,
                        rb_received_time: String,
                        rb_storage_time: String,
                        rb_delivery_time: String,
                        rb_update_time: String,
                        box_length: String,
                        box_width: String,
                        box_height: String,
                        box_weight: String,
                        box_status: String,
                        reference_box_no: String,
                        sign_status: String,
                        sign_batch: String,
                        sign_time: String,
                        sign_user_id: String,
                        is_new_add: String,
                        rb_timestamp: String,
                        stock_code: String
                       )