package com.zongteng.ztetl.entity.gc_oms

case class ReturnOrders(
                         ro_id: String,
                         company_code: String,
                         refrence_no_platform: String,
                         refrence_no_warehouse: String,
                         refrence_no: String,
                         tracking_number: String,
                         receiving_code: String,
                         ro_code: String,
                         warehouse_id: String,
                         creater: String,
                         verifier: String,
                         expected_date: String,
                         receiving_exception: String,
                         ro_is_all: String,
                         ro_type: String,
                         ro_status: String,
                         ro_sync_status: String,
                         ro_process_type: String,
                         ro_create_type: String,
                         ro_desc: String,
                         ro_note: String,
                         ro_service_message: String,
                         ro_add_time: String,
                         ro_confirm_time: String,
                         ro_update_time: String,
                         ro_shipping_method: String,
                         services1: String,
                         services2: String,
                         logistics_type: String,
                         is_return: String,
                         ro_first_shelve_time: String,
                         ro_receiving_time: String,
                         ro_timestamp: String
                       )
