package com.zongteng.ztetl.common

import java.text.SimpleDateFormat
import java.util.Date

import com.zongteng.ztetl.api.SparkConfig
import com.zongteng.ztetl.util.Log
import org.apache.spark.sql.SparkSession

object DataToHiveUtil {
  def main(args: Array[String]): Unit = {
    val task: String = Log.start("Dw_dim_warehouse_area")
    try {
      val spark: SparkSession = SparkConfig.init("DataToHiveUtil")

      var w_insert_dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date)
      var w_update_dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date)
      val tuples: List[(String, String, String, String, String, String, String, String, String)] = List(
        ("9001", "value_added_tax", "0", "否", "否", "gc_oms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9001", "value_added_tax", "1", "是", "是", "gc_oms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9001", "saving_time", "1", "夏令时", "夏令时", "gc_oms_warehouse", "令时", w_insert_dt, w_update_dt),
        ("9001", "saving_time", "0", "冬令时", "冬令时", "gc_oms_warehouse", "令时", w_insert_dt, w_update_dt),
        ("9001", "warehouse_type", "0", "标准", "标准", "gc_oms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9001", "warehouse_type", "1", "中转", "中转", "gc_oms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9001", "warehouse_status", "1", "可用", "可用", "gc_oms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9001", "warehouse_status", "0", "不可用", "不可用", "gc_oms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9001", "warehouse_virtual", "0", "自营", "自营", "gc_oms_warehouse", "", w_insert_dt, w_update_dt),
        ("9001", "warehouse_virtual", "1", "第三方", "第三方", "gc_oms_warehouse", "", w_insert_dt, w_update_dt),
        ("9001", "warehouse_transfer", "0", "标准", "标准", "gc_oms_warehouse", "", w_insert_dt, w_update_dt),
        ("9001", "warehouse_transfer", "1", "中转", "中转", "gc_oms_warehouse", "", w_insert_dt, w_update_dt),
        ("9004", "value_added_tax", "0", "否", "否", "gc_wms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9004", "value_added_tax", "1", "是", "是", "gc_wms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9004", "saving_time", "1", "夏令时", "夏令时", "gc_wms_warehouse", "令时", w_insert_dt, w_update_dt),
        ("9004", "saving_time", "0", "冬令时", "冬令时", "gc_wms_warehouse", "令时", w_insert_dt, w_update_dt),
        ("9004", "warehouse_type", "0", "标准", "标准", "gc_wms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9004", "warehouse_type", "1", "中转", "中转", "gc_wms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9004", "warehouse_status", "1", "可用", "可用", "gc_wms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9004", "warehouse_status", "0", "不可用", "不可用", "gc_wms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9004", "warehouse_virtual", "0", "自营", "自营", "gc_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9004", "warehouse_virtual", "1", "第三方", "第三方", "gc_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9004", "warehouse_transfer", "0", "标准", "标准", "gc_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9004", "warehouse_transfer", "1", "中转", "中转", "gc_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9022", "value_added_tax", "0", "否", "否", "zy_wms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9022", "value_added_tax", "1", "是", "是", "zy_wms_warehouse", "是否开启增值税审核", w_insert_dt, w_update_dt),
        ("9022", "warehouse_type", "0", "标准", "标准", "zy_wms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9022", "warehouse_type", "1", "中转", "中转", "zy_wms_warehouse", "仓库类型", w_insert_dt, w_update_dt),
        ("9022", "warehouse_status", "1", "可用", "可用", "zy_wms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9022", "warehouse_status", "0", "不可用", "不可用", "zy_wms_warehouse", "仓库状态", w_insert_dt, w_update_dt),
        ("9022", "warehouse_virtual", "0", "自营", "自营", "zy_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9022", "warehouse_virtual", "1", "第三方", "第三方", "zy_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9022", "warehouse_transfer", "0", "标准", "标准", "zy_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9022", "warehouse_transfer", "1", "中转", "中转", "zy_wms_warehouse", "", w_insert_dt, w_update_dt),
        ("9004", "wp_status", "0", "不可用", "不可用", "gc_wms_warehouse_physical", "状态", w_insert_dt, w_update_dt),
        ("9004", "wp_status", "1", "可用", "可用", "gc_wms_warehouse_physical", "状态", w_insert_dt, w_update_dt),
        ("9004", "wa_status", "0", "不可用", "不可用", "gc_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9004", "wa_status", "1", "可用", "可用", "gc_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9004", "wa_status", "-1", "已废弃", "已废弃", "gc_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9022", "wa_status", "0", "不可用", "不可用", "zy_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9022", "wa_status", "1", "可用", "可用", "zy_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9022", "wa_status", "-1", "已废弃", "已废弃", "zy_wms_warehouse_area", "", w_insert_dt, w_update_dt),
        ("9004", "contain_battery", "0", "普货", "普货", "gc_wms_location", "货物属性", w_insert_dt, w_update_dt),
        ("9004", "contain_battery", "1", "含电", "含电", "gc_wms_location", "货物属性", w_insert_dt, w_update_dt),
        ("9004", "contain_battery", "2", "纯电", "纯电", "gc_wms_location", "货物属性", w_insert_dt, w_update_dt),
        ("9004", "contain_battery", "3", "无限制", "无限制", "gc_wms_location", "货物属性", w_insert_dt, w_update_dt),
        ("9004", "is_mixed", "0", "否", "否", "gc_wms_location", "是否混放", w_insert_dt, w_update_dt),
        ("9004", "is_mixed", "1", "是", "是", "gc_wms_location", "是否混放", w_insert_dt, w_update_dt),
        ("9004", "is_multiple_batch", "0", "否", "否", "gc_wms_location", "是否多批次", w_insert_dt, w_update_dt),
        ("9004", "is_multiple_batch", "1", "是", "是", "gc_wms_location", "是否多批次", w_insert_dt, w_update_dt),
        ("9004", "lc_status", "1", "可用", "可用", "gc_wms_location", "", w_insert_dt, w_update_dt),
        ("9004", "lc_status", "0", "已废弃", "已废弃", "gc_wms_location", "", w_insert_dt, w_update_dt),
        ("9004", "lc_status", "-1", "已废弃", "已废弃", "gc_wms_location", "", w_insert_dt, w_update_dt),
        ("9022", "lc_status", "1", "可用", "可用", "zy_wms_location", "", w_insert_dt, w_update_dt),
        ("9022", "lc_status", "0", "已废弃", "已废弃", "zy_wms_location", "", w_insert_dt, w_update_dt),
        ("9022", "lc_status", "-1", "已废弃", "已废弃", "zy_wms_location", "", w_insert_dt, w_update_dt),
        ("9004", "currency_local", "1", "Y", "Y", "gc_wms_currency", "", w_insert_dt, w_update_dt),
        ("9004", "currency_local", "0", "N", "N", "gc_wms_currency", "", w_insert_dt, w_update_dt),
        ("9022", "currency_local", "1", "Y", "Y", "zy_wms_currency", "", w_insert_dt, w_update_dt),
        ("9022", "currency_local", "0", "N", "N", "zy_wms_currency", "", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "0", "良品", "良品", "gc_wms_gc_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "1", "不良品", "不良品", "gc_wms_gc_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "2", "备货(良品)", "备货(良品)", "gc_wms_gc_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_status", "0", "待上架", "待上架", "gc_wms_gc_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9004", "pd_status", "1", "已完成", "已完成", "gc_wms_gc_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "0", "良品", "良品", "gc_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "1", "不良品", "不良品", "gc_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_inventory_type", "2", "备货(良品)", "备货(良品)", "gc_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9004", "pd_status", "0", "待上架", "待上架", "gc_wms_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9004", "pd_status", "1", "已完成", "已完成", "gc_wms_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9022", "pd_inventory_type", "0", "良品", "良品", "zy_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9022", "pd_inventory_type", "1", "不良品", "不良品", "zy_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9022", "pd_inventory_type", "2", "备货(良品)", "备货(良品)", "zy_wms_putaway_detail", "库存类型", w_insert_dt, w_update_dt),
        ("9022", "pd_status", "0", "待上架", "待上架", "zy_wms_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9022", "pd_status", "1", "已完成", "已完成", "zy_wms_putaway_detail", "上架状态", w_insert_dt, w_update_dt),
        ("9001", "is_qc", "0", "N", "N", "gc_oms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9001", "is_qc", "1", "Y", "Y", "gc_oms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9001", "is_priority", "0", "N", "N", "gc_oms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9001", "is_priority", "1", "Y", "Y", "gc_oms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9001", "is_new_add", "1", "是", "是", "gc_oms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9001", "is_new_add", "0", "否", "否", "gc_oms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9001", "rd_status", "-1", "删除", "删除", "gc_oms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9001", "rd_status", "0", "在途", "在途", "gc_oms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9001", "rd_status", "1", "收货中", "收货中", "gc_oms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9001", "rd_status", "2", "收货完成", "收货完成", "gc_oms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "0", "删除", "删除", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "1", "草稿", "草稿", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "5", "尾程在途(头程出口)", "尾程在途(头程出口)", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "6", "尾程收货中", "尾程收货中", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "7", "尾程收货完成", "尾程收货完成", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "8", "尾程上架完成", "尾程上架完成", "gc_wms_gc_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "1", "是", "是", "gc_wms_gc_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "0", "否", "否", "gc_wms_gc_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_qc", "0", "N", "N", "gc_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9004", "is_qc", "1", "Y", "Y", "gc_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9004", "is_priority", "0", "N", "N", "gc_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9004", "is_priority", "1", "Y", "Y", "gc_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "-1", "删除", "删除", "gc_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "0", "在途", "在途", "gc_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "1", "收货中", "收货中", "gc_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rd_status", "2", "收货完成", "收货完成", "gc_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "1", "是", "是", "gc_wms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "0", "否", "否", "gc_wms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9022", "is_qc", "0", "N", "N", "zy_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9022", "is_qc", "1", "Y", "Y", "zy_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9022", "is_priority", "0", "N", "N", "zy_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9022", "is_priority", "1", "Y", "Y", "zy_wms_receiving_detail", "", w_insert_dt, w_update_dt),
        ("9022", "is_new_add", "1", "是", "是", "zy_wms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9022", "is_new_add", "0", "否", "否", "zy_wms_receiving_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9022", "rd_status", "-1", "删除", "删除", "zy_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9022", "rd_status", "0", "在途", "在途", "zy_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9022", "rd_status", "1", "收货中", "收货中", "zy_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9022", "rd_status", "2", "收货完成", "收货完成", "zy_wms_receiving_detail", "收货状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "0", "删除(入库单删除或者箱号删除)", "删除(入库单删除或者箱号删除)", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "1", "草稿", "草稿", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "5", "尾程在途", "尾程在途", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "6", "尾程收货中", "尾程收货中", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "7", "尾程收货完成", "尾程收货完成", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "rbd_status", "8", "上架完成", "上架完成", "gc_wms_gc_receiving_box_detail", "状态", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "1", "是", "是", "gc_wms_gc_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "0", "否", "否", "gc_wms_gc_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "1", "是", "是", "gc_wms_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9004", "is_new_add", "0", "否", "否", "gc_wms_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9022", "is_new_add", "1", "是", "是", "zy_wms_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),
        ("9022", "is_new_add", "0", "否", "否", "zy_wms_receiving_box_detail", "是否新增", w_insert_dt, w_update_dt),

        // dim_employee - 6
        (SystemCodeUtil.GC_OMS, "user_status", "0",	 "",	      "",	       "gc_oms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS,	"user_status", "1",  "审核通过",	"审核通过", "gc_oms_user", "用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS,	"user_status", "2",  "待审核",	  "待审核",	 "gc_oms_user", "用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_WMS,	"user_status", "0",  "",	      "",	       "gc_wms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_WMS,	"user_status", "1",  "在职",     "在职",	   "gc_wms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_WMS,	"user_status", "-1", "离职",   	"离职",	   "gc_wms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.ZY_WMS,	"user_status", "0",	 "",	      "",	       "zy_wms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.ZY_WMS,	"user_status", "1",	 "在职", 	  "在职",	   "zy_wms_user",	"用户状态", w_insert_dt, w_update_dt),
        (SystemCodeUtil.ZY_WMS,	"user_status", "-1", "离职",    "离职",	   "zy_wms_user",	"用户状态", w_insert_dt, w_update_dt),

        // dim_customer - 4
        (SystemCodeUtil.GC_WMS,	"cash_type", "1", "预付", "预付", "gc_wms_customer",	"资金类型", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_WMS,	"cash_type", "2", "月结", "月结", "gc_wms_customer",	"资金类型", w_insert_dt, w_update_dt),
        (SystemCodeUtil.ZY_WMS,	"cash_type", "1", "预付", 	"预付", "zy_wms_customer",	"资金类型", w_insert_dt, w_update_dt),
        (SystemCodeUtil.ZY_WMS,	"cash_type", "2", "月结",  "月结", "zy_wms_customer", "资金类型", w_insert_dt, w_update_dt),

          // dim_product - GC_OMS - 25
        (SystemCodeUtil.GC_OMS, "product_status","1", "可用", "可用", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_status","2", "草稿", "草稿", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_status","3", "审核中", "审核中", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_status","0", "废弃", "废弃", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_status","4", "审核不通过", "审核不通过", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "is_thirdpart","1", "非第三方", "非第三方", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "is_thirdpart","2", "第三方", "第三方", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "sale_status","1", "正常销售", "正常销售", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_receive_status","0", "新产品", "新产品", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_receive_status","1", "已收货", "已收货", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_is_qc","0", "N", "N", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_is_qc","1", "Y", "Y", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_barcode_type","0", "普通产品", "普通产品", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_type","0", "普通产品", "普通产品", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "shared_sign","0", "N", "N", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "shared_sign","1", "Y", "Y", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "contain_battery","0", "普货", "普货", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "contain_battery","1", "含电池", "含电池", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "contain_battery","2", "纯电池", "纯电池", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "contain_battery","3", "纺织品", "纺织品", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "contain_battery","4", "易碎品", "易碎品", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_package_type","package", "包裹", "包裹", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "product_package_type","letter", "信封", "信封", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "cat_lang","zh", "中文", "中文", "gc_oms_product", "", w_insert_dt, w_update_dt),
        (SystemCodeUtil.GC_OMS, "cat_lang","en", "英文", "英文", "gc_oms_product", "", w_insert_dt, w_update_dt),

        (SystemCodeUtil.GC_WMS, "product_status", "1",  "正式产品",  "正式产品", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_status", "2",  "草稿",  "草稿", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_status", "3",  "待审核",  "待审核", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_status", "4",  "驳回",  "驳回", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_status", "0",  "下架产品",  "下架产品", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "is_thirdpart", "1",  "非第三方",  "非第三方", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "is_thirdpart", "2",  "第三方",  "第三方", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "is_irregular", "0",  "否",  "否", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "is_irregular", "1",  "是",  "是", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_receive_status", "0",  "新产品",  "新产品", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_receive_status", "1",  "已收货",  "已收货", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_package_type", "0",  "包裹",  "包裹", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "product_package_type", "1",  "信封",  "信封", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "contain_battery", "0",  "普货",  "普货", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "contain_battery", "1",  "含电池",  "含电池", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "contain_battery", "2",  "纯电池",  "纯电池", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "contain_battery", "3",  "纺织品",  "纺织品", "gc_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_WMS, "contain_battery", "4",  "易碎品",  "易碎品", "gc_wms_product",  "", w_insert_dt,  w_update_dt),

        (SystemCodeUtil.GC_BSC, "ProductStatus", "0",  "废弃",  "废弃", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductStatus", "1",  "可用",  "可用", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductStatus", "2",  "草稿",  "草稿", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductStatus", "3",  "审核中/待审核[后台]",  "审核中/待审核[后台]", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductStatus", "4",  "驳回",  "驳回", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReceiveStatus", "0",  "新产品",  "新产品", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReceiveStatus", "1",  "已收货",  "已收货", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "CategoryLanguage", "zh",  "中文",  "中文", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "CategoryLanguage", "en",  "英文",  "英文", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "GoodsAttribute", "0",  "普货",  "普货", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "GoodsAttribute", "1",  "含电池",  "含电池", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "GoodsAttribute", "2",  "纯电池",  "纯电池", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "GoodsAttribute", "3",  "纺织品",  "纺织品", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "GoodsAttribute", "4",  "易碎品",  "易碎品", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductPackageType", "0",  "包裹",  "包裹", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ProductPackageType", "1",  "信封",  "信封", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsThirdPart", "0",  "非第三方",  "非第三方", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsThirdPart", "1",  "第三方",  "第三方", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsBrand", "0",  "否",  "否", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsBrand", "1",  "是",  "是", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsDeployControl", "1",  "否",  "否", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsDeployControl", "2",  "是",  "是", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReVerifyStatus", "0",  "未复核",  "未复核", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReVerifyStatus", "1",  "复核中",  "复核中", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReVerifyStatus", "2",  "免复核/复核完成",  "免复核/复核完成", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReVerifyStatus", "3",  "申诉中",  "申诉中", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "ReVerifyStatus", "4",  "申诉完成",  "申诉完成", "gc_bsc_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsIrregular", "0",  "否",  "否", "gc_bsc_productExtend",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.GC_BSC, "IsIrregular", "1",  "是",  "是", "gc_bsc_productExtend",  "", w_insert_dt,  w_update_dt),
        
        (SystemCodeUtil.ZY_WMS, "product_status", "1",  "正式产品",  "正式产品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_status", "2",  "待审核",  "待审核", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_status", "3",  "驳回",  "驳回", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_status", "0",  "下架产品",  "下架产品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "sale_status", "1",  "正常销售",  "正常销售", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "is_thirdpart", "1",  "非第三方",  "非第三方", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "is_thirdpart", "2",  "第三方",  "第三方", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_receive_status", "0",  "新产品",  "新产品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_receive_status", "1",  "已收货",  "已收货", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_is_qc", "0",  "N",  "N", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_is_qc", "1",  "Y",  "Y", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_barcode_type", "0",  "普通产品",  "普通产品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_type", "0",  "普通产品",  "普通产品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "shared_sign", "0",  "N",  "N", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "shared_sign", "1",  "Y",  "Y", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "contain_battery", "0",  "普货",  "普货", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "contain_battery", "1",  "含电池",  "含电池", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "contain_battery", "2",  "纯电池",  "纯电池", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "contain_battery", "3",  "纺织品",  "纺织品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "contain_battery", "4",  "易碎品",  "易碎品", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_package_type", "package",  "包裹",  "包裹", "zy_wms_product",  "", w_insert_dt,  w_update_dt),
        (SystemCodeUtil.ZY_WMS, "product_package_type", "letter",  "信封",  "信封", "zy_wms_product",  "", w_insert_dt,  w_update_dt),

         // dim_shipping_method
          ("9004", "sm_code_type", "0", "头程物流产品", "头程物流产品", "gc_wms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9004", "sm_code_type", "1", "退件物流产品", "退件物流产品", "gc_wms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9004", "sm_is_more_box", "0", "一票一箱", "一票一箱", "gc_wms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9004", "sm_is_more_box", "1", "一票多箱", "一票多箱", "gc_wms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9004", "sm_is_claim", "0", "否", "否", "gc_wms_shipping_method", "是否支持索赔", w_insert_dt, w_update_dt),
          ("9004", "sm_is_claim", "1", "是", "是", "gc_wms_shipping_method", "是否支持索赔", w_insert_dt, w_update_dt),
          ("9004", "sm_age_detection", "0", "否", "否", "gc_wms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9004", "sm_age_detection", "1", "是", "是", "gc_wms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9004", "sm_volume_type", "1", "按比例进位", "按比例进位", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_volume_type", "2", "四舍五入取整", "四舍五入取整", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_volume_type", "3", "四舍五入取整保留一位小数", "四舍五入取整保留一位小数", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_weight_type", "1", "按比例进位", "按比例进位", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_weight_type", "2", "四舍五入取整", "四舍五入取整", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_weight_type", "3", "四舍五入取整保留一位小数", "四舍五入取整保留一位小数", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sfp_label_type", "1", "DSV", "DSV", "gc_wms_shipping_method", "自提面单格式", w_insert_dt, w_update_dt),
          ("9004", "sfp_label_type", "2", "SFP", "SFP", "gc_wms_shipping_method", "自提面单格式", w_insert_dt, w_update_dt),
          ("9004", "life_gate", "0", "否", "否", "gc_wms_shipping_method", "升降梯服务", w_insert_dt, w_update_dt),
          ("9004", "life_gate", "1", "是", "是", "gc_wms_shipping_method", "升降梯服务", w_insert_dt, w_update_dt),
          ("9004", "sm_truck", "0", "否", "否", "gc_wms_shipping_method", "卡车服务", w_insert_dt, w_update_dt),
          ("9004", "sm_truck", "1", "是", "是", "gc_wms_shipping_method", "卡车服务", w_insert_dt, w_update_dt),
          ("9004", "sm_is_volume", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_volume", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_charge", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_charge", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_validate_remote", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_validate_remote", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_tracking", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_tracking", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_signature", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_signature", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_insurance", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_is_insurance", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_type", "0", "快递", "快递", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_type", "1", "空运", "空运", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_type", "2", "海运", "海运", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_type", "3", "小包", "小包", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_class_code", "CRE", "快递", "快递", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_class_code", "CRP", "挂号", "挂号", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_class_code", "CPS", "平邮", "平邮", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_status", "0", "不可用", "不可用", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_status", "1", "可用", "可用", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_allow_letter", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "sm_allow_letter", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "pre_generate_label", "0", "N", "N", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9004", "pre_generate_label", "1", "Y", "Y", "gc_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_code_type", "0", "头程物流产品", "头程物流产品", "zy_wms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9022", "sm_code_type", "1", "退件物流产品", "退件物流产品", "zy_wms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9022", "sm_is_more_box", "0", "一票一箱", "一票一箱", "zy_wms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9022", "sm_is_more_box", "1", "一票多箱", "一票多箱", "zy_wms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9022", "sm_attribute", "0", "普货", "普货", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_attribute", "1", "含电池", "含电池", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_attribute", "2", "纯电池", "纯电池", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_attribute", "3", "通用", "通用", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_claim", "0", "否", "否", "zy_wms_shipping_method", "是否支持索赔", w_insert_dt, w_update_dt),
          ("9022", "sm_is_claim", "1", "是", "是", "zy_wms_shipping_method", "是否支持索赔", w_insert_dt, w_update_dt),
          ("9022", "sm_age_detection", "0", "否", "否", "zy_wms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9022", "sm_age_detection", "1", "是", "是", "zy_wms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9022", "sm_is_volume", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_volume", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_charge", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_charge", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_validate_remote", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_validate_remote", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_tracking", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_tracking", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_signature", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_signature", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_insurance", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_is_insurance", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_type", "0", "快递", "快递", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_type", "1", "空运", "空运", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_type", "2", "海运", "海运", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_type", "3", "小包", "小包", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_class_code", "CRE", "快递", "快递", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_class_code", "CRP", "挂号", "挂号", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_class_code", "CPS", "平邮", "平邮", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_status", "0", "不可用", "不可用", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_status", "1", "可用", "可用", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_allow_letter", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "sm_allow_letter", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "pre_generate_label", "0", "N", "N", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9022", "pre_generate_label", "1", "Y", "Y", "zy_wms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_code_type", "0", "头程物流产品", "头程物流产品", "gc_oms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9001", "sm_code_type", "1", "退件物流产品", "退件物流产品", "gc_oms_shipping_method", "产品类型", w_insert_dt, w_update_dt),
          ("9001", "sm_is_more_box", "0", "一票一箱", "一票一箱", "gc_oms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9001", "sm_is_more_box", "1", "一票多箱", "一票多箱", "gc_oms_shipping_method", "装箱类型", w_insert_dt, w_update_dt),
          ("9001", "sm_age_detection", "0", "否", "否", "gc_oms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9001", "sm_age_detection", "1", "是", "是", "gc_oms_shipping_method", "年龄检测服务", w_insert_dt, w_update_dt),
          ("9001", "life_gate", "0", "否", "否", "gc_oms_shipping_method", "升降梯服务", w_insert_dt, w_update_dt),
          ("9001", "life_gate", "1", "是", "是", "gc_oms_shipping_method", "升降梯服务", w_insert_dt, w_update_dt),
          ("9001", "sm_truck", "0", "否", "否", "gc_oms_shipping_method", "卡车服务", w_insert_dt, w_update_dt),
          ("9001", "sm_truck", "1", "是", "是", "gc_oms_shipping_method", "卡车服务", w_insert_dt, w_update_dt),
          ("9001", "sm_is_volume", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_volume", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_charge", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_charge", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_validate_remote", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_validate_remote", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_tracking", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_tracking", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_signature", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_signature", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_insurance", "0", "N", "N", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_is_insurance", "1", "Y", "Y", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_type", "0", "快递", "快递", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_type", "1", "空运", "空运", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_type", "2", "海运", "海运", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_type", "3", "小包", "小包", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_class_code", "CRE", "快递", "快递", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_class_code", "CRP", "挂号", "挂号", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_class_code", "CPS", "平邮", "平邮", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_status", "0", "不可用", "不可用", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),
          ("9001", "sm_status", "1", "可用", "可用", "gc_oms_shipping_method", "", w_insert_dt, w_update_dt),

          // fact_receiving_box
          ("9004","is_new_add", "0", "否", "否", "gc_wms_gc_receiving_box", "是否是新增箱子", w_insert_dt, w_update_dt),
          ("9004","is_new_add", "1", "是", "是", "gc_wms_gc_receiving_box", "是否是新增箱子", w_insert_dt, w_update_dt),
          ("9004","sign_status", "0", "未签收", "未签收", "gc_wms_gc_receiving_box", "签收状态", w_insert_dt, w_update_dt),
          ("9004","sign_status", "1", "已签收", "已签收", "gc_wms_gc_receiving_box", "签收状态", w_insert_dt, w_update_dt),
          ("9022","is_new_add", "0", "否", "否", "zy_wms_receiving_box", "是否是新增箱子", w_insert_dt, w_update_dt),
          ("9022","is_new_add", "1", "是", "是", "zy_wms_receiving_box", "是否是新增箱子", w_insert_dt, w_update_dt),
          ("9022","sign_status", "0", "未签收", "未签收", "zy_wms_receiving_box", "签收状态", w_insert_dt, w_update_dt),
          ("9022","sign_status", "1", "已签收", "已签收", "zy_wms_receiving_box", "签收状态", w_insert_dt, w_update_dt),
          ("9022","rb_transfer_status", "0", "未收货", "未收货", "zy_wms_receiving_box", "转移状态", w_insert_dt, w_update_dt),
          ("9022","rb_transfer_status", "1", "收货中", "收货中", "zy_wms_receiving_box", "转移状态", w_insert_dt, w_update_dt),
          ("9022","rb_transfer_status", "2", "收货完成", "收货完成", "zy_wms_receiving_box", "转移状态", w_insert_dt, w_update_dt),

           // fact_receiving
            ("9001", "create_type", "hand", "手动创建", "手动创建", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "create_type", "api", "系统创建", "系统创建", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "0", "空运", "空运", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "1", "海运", "海运", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "2", "快递", "快递", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "0", "未签收", "未签收", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "1", "签收中", "签收中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "2", "签收完成", "签收完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "is_change_sku", "1", "不换标", "不换标", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "is_change_sku", "2", "换标", "换标", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "is_third", "1", "非第三方", "非第三方", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "is_third", "2", "第三方", "第三方", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "0", "废弃", "废弃", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "10", "待审核", "待审核", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "50", "头程在途", "头程在途", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "60", "头程收货中", "头程收货中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "71", "转运中", "转运中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "72", "目的仓收货中", "目的仓收货中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "73", "目的仓收货完成", "目的仓收货完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_status", "74", "目的仓上架完成", "目的仓上架完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "income_type", "0", "自送", "自送", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "income_type", "1", "上门揽收", "上门揽收", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_transfer_status", "0", "草稿", "草稿", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_transfer_status", "1", "待处理", "待处理", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_transfer_status", "2", "处理中", "处理中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_transfer_status", "3", "处理完成", "处理完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_transfer_status", "4", "上架完成", "上架完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "0", "空运", "空运", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "1", "海运散货", "海运散货", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "2", "快递", "快递", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "3", "铁运", "铁运", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_shipping_type", "4", "海运整柜", "海运整柜", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "0", "未签收", "未签收", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "1", "签收中", "签收中", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "rv_sign_status", "2", "签收完成", "签收完成", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "tax_type", "P", "实物报销", "实物报销", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "customer_type", "Y", "委托报关", "委托报关", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "customer_type", "N", "客户自理", "客户自理", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "customer_type", "E", "EDI报关", "EDI报关", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_type", "0", "自发头程", "自发头程", "gc_oms_receiving", "", w_insert_dt, w_update_dt),
            ("9001", "receiving_type", "3", "中转代发", "中转代发", "gc_oms_receiving", "", w_insert_dt, w_update_dt),


            ("9004", "income_type", "0", "自送", "自送", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "income_type", "1", "揽收", "揽收", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_shipping_type", "0", "空运", "空运", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_shipping_type", "1", "海运", "海运", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_shipping_type", "2", "快递", "快递", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_shipping_type", "3", "铁运", "铁运", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_shipping_type", "4", "海运整柜", "海运整柜", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "receiving_type", "0", "标准", "标准", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_type", "3", "中转（易渡代发）", "中转（易渡代发）", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_type", "4", "原标入库", "原标入库", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_type", "5", "FBA入库单", "FBA入库单", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "0", "删除废弃", "删除废弃", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "1", "草稿(待审核)", "草稿(待审核)", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "5", "在途", "在途", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "6", "收货中", "收货中", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "7", "收货完成(上架中)", "收货完成(上架中)", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "receiving_status", "8", "上架完成", "上架完成", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "create_type", "hand", "手动创建", "手动创建", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "create_type", "api", "系统创建", "系统创建", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "rv_sign_status", "0", "未签收", "未签收", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "rv_sign_status", "1", "签收中", "签收中", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "rv_sign_status", "2", "签收完成", "签收完成", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "is_send_email", "1", "不发送邮件", "不发送邮件", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "is_send_email", "2", "发送邮件", "发送邮件", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "email_result", "1", "发送失败", "发送失败", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "email_result", "2", "发送成功", "发送成功", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "email_result", "3", "未知", "未知", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "is_diff", "1", "无差异", "无差异", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "is_diff", "2", "有差异", "有差异", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "diff_sure_status", "1", "无差异", "无差异", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "diff_sure_status", "2", "未确认", "未确认", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "diff_sure_status", "3", "已确认", "已确认", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "vat_status", "1", "待审核", "待审核", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "vat_status", "2", "审核通过", "审核通过", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "vat_status", "3", "审核驳回", "审核驳回", "gc_wms_gc_receiving", "", w_insert_dt,  w_update_dt),
            ("9004", "file_status", "1", "未上传", "未上传", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),
            ("9004", "file_status", "2", "已上传", "已上传", "gc_wms_gc_receiving", "", w_insert_dt, w_update_dt),

            ("9022", "sync_owms_status", "", "", "", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "sync_owms_sign", "", "", "", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "create_type", "hand", "手动创建", "手动创建", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "create_type", "api", "系统创建", "系统创建", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_shipping_type", "0", "空运", "空运", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_shipping_type", "1", "海运", "海运", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_shipping_type", "2", "快递", "快递", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_shipping_type", "3", "铁运", "铁运", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_shipping_type", "4", "海运整柜", "海运整柜", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "rv_sign_status", "0", "未签收", "未签收", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "rv_sign_status", "1", "签收中", "签收中", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "rv_sign_status", "2", "签收完成", "签收完成", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_fee", "0", "否", "否", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_fee", "1", "是", "是", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_change_sku", "1", "不换标", "不换标", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_change_sku", "2", "换标", "换标", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_third", "1", "非第三方", "非第三方", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_third", "2", "第三方", "第三方", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "vat_status", "1", "待审核", "待审核", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "vat_status", "2", "审核通过", "审核通过", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "vat_status", "3", "审核驳回", "审核驳回", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "vat_status", "4", "未上传", "未上传", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_cost_fee", "0", "未头程计费", "未头程计费", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "is_cost_fee", "1", "已头程计费", "已头程计费", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "income_type", "0", "自送", "自送", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "income_type", "1", "揽收", "揽收", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_transfer_status", "0", "草稿", "草稿", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_transfer_status", "1", "待处理", "待处理", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_transfer_status", "2", "处理中", "处理中", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_transfer_status", "3", "处理完成", "处理完成", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "receiving_transfer_status", "4", "上架完成", "上架完成", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "tax_type", "P", "实物报销", "实物报销", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "customer_type", "Y", "委托报关", "委托报关", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "customer_type", "N", "客户自理", "客户自理", "zy_wms_receiving", "", w_insert_dt, w_update_dt),
            ("9022", "customer_type", "E", "EDI报关", "EDI报关", "zy_wms_receiving", "", w_insert_dt, w_update_dt)
      )


      val builder: StringBuilder = new StringBuilder

      builder.append("insert overwrite table dw.par_val_list values  ")
      var i = 0;

      for (elem <- tuples) {
        //val parvallist = PAR_VAL_LIST(elem._1,elem._2,elem._3,elem._4,elem._5,elem._6,elem._7,elem._8)
        if (i == tuples.size - 1) {
          builder.append(s"(\'${elem._1}\',\'${elem._2}\',\'${elem._3}\',\'${elem._4}\',\'${elem._5}\',\'${elem._6}\',\'${elem._7}\',\'${elem._8}\',\'${elem._9}\')")
        } else {
          builder.append(s"(\'${elem._1}\',\'${elem._2}\',\'${elem._3}\',\'${elem._4}\',\'${elem._5}\',\'${elem._6}\',\'${elem._7}\',\'${elem._8}\',\'${elem._9}\'),")
        }
        i += 1;
      }

      println(builder.toString)

//      spark.sql(builder.toString)

      spark.sql("show databases");

      spark.stop()
      Log.end(task)
    } catch {
      case ex: Exception => Log.error(task, ex)
    }
  }

  case class PAR_VAL_LIST(datasource_num_id: String, vl_type: String, vl_value: String, vl_name: String, vl_bi_name: String, vl_memo: String, w_insert_dt: String, w_update_dt: String)

  /*def main(args: Array[String]): Unit = {
    val task: String = Log.start("DataToHiveUtil")
    try{
      val spark: SparkSession = SparkConfig.init("DataToHiveUtil")
      val lines: RDD[String] = spark.sparkContext.textFile("src/par_val_hive")
      var w_insert_dt      =""
      var w_update_dt      =""
      var par_val_list:PAR_VAL_LIST=null
      val par_val_lists: RDD[PAR_VAL_LIST] = lines.map(line => {
        println(line)
        val vals: Array[String] = line.split(",")
        w_insert_dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date)
        w_update_dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date)
        println(vals.size)
        if(vals.size>=6){
          par_val_list = PAR_VAL_LIST(vals(0).toString, vals(1).toString, vals(2).toString, vals(3).toString, vals(4).toString, vals(5).toString, w_insert_dt, w_update_dt)
        }
        par_val_list
      })
      par_val_lists.foreach(println(_))
      val par_val: DataFrame = spark.createDataFrame(par_val_lists,PAR_VAL_LIST.getClass)
      par_val.createOrReplaceGlobalTempView("parval")
      val value: DataFrame = spark.sql("select pl.datasource_num_id,pl.vl_type,vl_value,pl.vl_name,pl.vl_bi_name,pl.vl_memo,pl.w_insert_dt,pl.w_update_dt from parval pl")
      SparkDataFrame.save(value,"dw","par_val_list")

      spark.stop()
      Log.end(task)
    }catch {
      case ex:Exception=>Log.error(task,ex)
    }

  }*/

}
