package com.zongteng.ztetl.entity.gc_wms

case class BilIncome(
                bi_id: String,
                bcb_id: String,
                customer_code: String,
                bi_withdraw_sign: String,
                bb_id: String,
                ft_code: String,
                ut_code: String,
                sm_code: String,
                bi_creator_id: String,
                bi_verifier_id: String,
                bi_amount: String,
                bi_org_amount: String,
                currency_code: String,
                currency_rate: String,
                bi_note: String,
                bi_create_type: String,
                bi_rp_type: String,
                bi_status: String,
                bi_balance_sign: String,
                bi_return_sign: String,
                bi_chargeable_time: String,
                bi_add_time: String,
                bi_verify_time: String,
                bi_update_time: String,
                allow_create_bill: String,
                allow_create_bill_time: String,
                parent_ft_code: String,
                remark_code: String,
                create_currency_code: String,
                update_time: String,
                update_user: String
)
