package com.zongteng.ztetl.entity.zy_wms

case class AfterSalesReturnOrders (
                                    asro_id:String,
                                    asro_code:String,
                                    tracking_no:String,
                                    reference_no:String,
                                    customer_code:String,
                                    order_code:String,
                                    warehouse_id:String,
                                    cass_type:String,
                                    cass_auth_type:String,
                                    asro_status:String,
                                    creater_user_id:String,
                                    asro_desc:String,
                                    asro_reason:String,
                                    asro_note:String,
                                    asro_sku_total:String,
                                    product_photos_qty:String,
                                    sm_code:String,
                                    sc_id:String,
                                    cass_is_diff:String,
                                    diff_process_status:String,
                                    sm_type:String,
                                    asro_add_time:String,
                                    asro_putaway_time:String,
                                    asro_audit_time:String,
                                    asro_update_time:String,
                                    received_time:String,
                                    to_be_confirmed_time:String,
                                    confirm_time:String
                                  )
